---
apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: cluster
  namespace: openshift-operators
spec: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::660250927410:role/dscott-external-secrets
  name: external-secrets
  namespace: vms
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets
  namespace: vms
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: vms
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:privileged
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: external-secrets
  namespace: vms
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrets
  namespace: vms
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: external-secrets
    kind: SecretStore
  target:
    name: external-secrets-demo
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: Demo
        property: username
    - secretKey: password
      remoteRef:
        key: Demo
        property: password
