---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vms
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
    - path: ./vms
      repoURL: 'https://github.com/scottd018-demos/openshift-virt-modernization'
      targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
