---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx
  namespace: vms
spec:
  to:
    kind: Service
    name: nginx
    weight: 100
  port:
    targetPort: 80
  wildcardPolicy: None
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: vms
spec:
  selector:
    app: route-policy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-specific-ip-range
  namespace: vms
spec:
  podSelector:
    matchLabels:
      app: route-policy
  policyTypes:
    - Ingress
  ingress:
    - from:
      - ipBlock:
          cidr: 10.10.0.0/16
          # cidr: 0.0.0.0/0
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: route-policy
  namespace: vms
  labels:
    app: route-policy
spec:
  dataVolumeTemplates:
    - metadata:
        name: route-policy
      spec:
        preallocation: false
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
          storageClassName: gp3-csi
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel9
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: route-policy
        kubevirt.io/size: small
    spec:
      accessCredentials:
        - sshPublicKey:
            propagationMethod:
              noCloud: {}
            source:
              secret:
                secretName: authorized-keys
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 32
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
            - bootOrder: 2
              disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
        machine:
          type: pc-q35-rhel9.2.0
        memory:
          guest: 32Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - dataVolume:
            name: route-policy
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: rhel
              password: xtg8-ly36-swy3
              chpasswd: { expire: False }
          name: cloudinitdisk
