---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: secrets
  namespace: vms
  labels:
    app: secrets
spec:
  dataVolumeTemplates:
    - metadata:
        name: secrets
      spec:
        preallocation: false
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
          storageClassName: gp3-csi
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel9
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: secrets
        kubevirt.io/size: small
    spec:
      accessCredentials:
        - sshPublicKey:
            propagationMethod:
              noCloud: {}
            source:
              secret:
                secretName: authorized-keys
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 32
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
            - bootOrder: 2
              disk:
                bus: virtio
              name: cloudinitdisk
            - name: external-secrets-demo
              serial: SECRET
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
        machine:
          type: pc-q35-rhel9.2.0
        memory:
          guest: 32Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: external-secrets-demo
          secret:
            secretName: external-secrets-demo
        - dataVolume:
            name: secrets
          name: rootdisk
        - cloudInitNoCloud:
            bootcmd:
              # TODO: expose secrets via nginx
              - "sudo mkdir /mnt/secrets"
              - "sudo mount /dev/$(lsblk --nodeps -no name,serial | grep SECRET | cut -f1 -d' ') /mnt/secrets"
              - "dnf install -y nginx"
            userData: |-
              #cloud-config
              user: rhel
              password: xtg8-ly36-swy3
              chpasswd: { expire: False }
          name: cloudinitdisk
