---
apiVersion: v1
kind: Service
metadata:
  name: secrets
  namespace: vms
spec:
  selector:
    app: secrets
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: secrets
  namespace: vms
spec:
  to:
    kind: Service
    name: secrets
    weight: 100
  port:
    targetPort: 80
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: secrets
  namespace: vms
  labels:
    app: secrets
spec:
  dataVolumeTemplates:
    - metadata:
        name: secrets
      spec:
        preallocation: false
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
          storageClassName: gp3-csi
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      labels:
        app: secrets
        kubevirt.io/domain: secrets
        kubevirt.io/size: small
    spec:
      accessCredentials:
        - sshPublicKey:
            propagationMethod:
              noCloud: {}
            source:
              secret:
                secretName: authorized-keys
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 24
          threads: 1
        resources:
          requests:
            cpu: 24
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
            - bootOrder: 2
              disk:
                bus: virtio
              name: cloudinitdisk
            - name: external-secrets-demo
              serial: SECRET
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
        machine:
          type: pc-q35-rhel9.2.0
        memory:
          guest: 32Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: external-secrets-demo
          secret:
            secretName: external-secrets-demo
        - dataVolume:
            name: secrets
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: xtg8-ly36-swy3
              chpasswd: { expire: False }
              runcmd:
                - sudo mkdir /mnt/secrets
                - sudo mount /dev/$(lsblk --nodeps -no name,serial | grep SECRET | cut -f1 -d' ') /mnt/secrets
                - sudo dnf install -y nginx
                - sudo cp /mnt/secrets/* /usr/share/nginx/html/
                - sudo umount /mnt/secrets
                - sudo systemctl enable nginx
                - |
                  sudo cat <<EOF > /usr/share/nginx/html/index.html
                  <html>
                  <body>
                  <h1>DEMO ONLY</h1><br>
                  <b>THIS DEMO SHOWS SECRETS SYNCED FROM EXTERNAL SECRETS</b><br>
                  <b>DO NOT DO THIS IN PRODUCTION</b><br>
                  <hr>
                  username=$(cat /usr/share/nginx/html/username)<br>
                  password=$(cat /usr/share/nginx/html/password)
                  </body>
                  </html>
                  EOF
                - sudo systemctl start nginx
          name: cloudinitdisk
